default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: increment_api_dev

test:
  <<: *default
  database: increment_api_test
  username: postgres
  password:
